# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.py'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      # image: openmc/openmc:latest-dagmc is missing the dagmc universe
      image: openmc/openmc:develop-dagmc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          python setup.py install

      - name: install packages for tests
        run: |
          pip install -r requirements-test.txt 

      - name: Run test_utils
        run: |
          python tests/create_statepoint_file_with_meshes_openmc.py --batches 2 --particles 100
          python tests/create_statepoint_file_with_meshes_openmc.py --batches 1 --particles 100
          pytest tests/ -v --cov=openmc_mesh_tally_to_vtk --cov-append --cov-report term --cov-report xml

      - name: Upload to codecov
        uses: codecov/codecov-action@v2

      # todo add examples
      # - name: Run examples
      #   run: |
      #     cd examples
      #     python create_statepoint_file_for_testing.py --batches 2 --particles 100
